### ISSUE TITLE
Add ParSys Jenkins to Dashboard

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/sso-dashboard-configuration#83]
Now that the [ParSys Jenkins](https://jenkins.services.mozilla.community/) is the first application leveraging [Mozillians.org groups for access management](https://mozillians.org/group/parsys-public-jenkins-access), might we want to [add it to the Dashboard](https://github.com/mozilla-iam/sso-dashboard-configuration/blob/master/apps.yml)? I'd like to hear some opinions and am happy to PR this (unless anybody else beats me to it).

Opinions? @andrewkrug @gdestuynder @flamingspaz @johngian @akatsoulas 

-Henrik

**Comment by gdestuynder** [comment]
np for me, though we probably should think about having this (which apps go in the dashboard) automated before it becomes too much to maintain manually

**Comment by johngian** [comment]
I don't have any strong opinion about that. My only concern is that any team might end up adding services to the dashboard regardless of the audience. This is going to cause some noise for the rest of the org.

**Comment by flamingspaz** [comment]
Jenkins has an audience of like 6 people, if its only visible for those 6 then im fine w it.

**Comment by hmitsch** [comment]
Great feedback @gdestuynder and @johngian!
How about a small architectural conversation at this point:

I understand the the following two parameters drive app visibility in the Dashboard:
> authorized_users
> authorized_groups

Currently, _authorized_groups_ might contain something like ` ['team_moco', 'team_mofo']`.

What's our plan for the future of these parameters? Will they be dynamically read from the profile/group management system, populated at runtime and therefore allow an **always up-to-date, user-specific view of available applications**?

I hope somebody can expand my model to help me understand.

Best regards,
   Henrik

**Comment by gdestuynder** [comment]
We can only read from the profile if and only if all dashboard apps are in Auth0.
I believe that right now there are exceptions to that (cc @jdow ) - if not, this would be the easiest.. with a caveat:

we do not know exactly which apps should be presented "to all users in group x", which is why we have this file. this is because historically apps weren't tied to users, but instead used various groups.
With the automatic expiration of access, we will known which apps are used by which user (in `authorizedGroups` in the user profile), but only after the user has logged in *at least once to the app*.

This means it would still need pre-provision, and/or a mapping of groups to client_ids (which could absolutely be done in CIS, but it's a medium tshirt size) - if done in CIS this would also effectively give some kind of CIS group mapping feature that allows for hierarchical view of groups (even thus in reality these are done in flat-view profiles).
Eg: group X = access to [list of client_ids] (which could also be enhanced by: group X = [list of sub groups OR client_ids, which themselves have list of client_ids] .
Due to being hierachical it adds complexity but at least the resolution would be done in CIS and not in the profile directly.

cc @andrewkrug whom I'm sure can decipher what I'm saying as he went through this pain at a previous job ;-)

In all cases, I wouldn't schedule this for now. The current solution works. This should go on the roadmap or something like that.

**Comment by andrewkrug** [comment]
@hmitsch is this still needed?  /me thinks not.

**Comment by hmitsch** [comment]
I agree with closing this. :-)
